### ISSUE TITLE
Widget Binding warning

### ISSUE THREAD

**Issue by ag-0214** [CHB61/multi_select_flutter#105]
Greetings.
After upgrading to the latest package, I am having this warning
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/multi_select_flutter-4.1.2/lib/chip_field/multi_select_chip_field.dart:273:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback((_) => _scrollToPosition());

Regards

**Comment by miguelflores1993** [comment]
are you going to correct it?

**Comment by kabagouda** [comment]
Hi 
The issue has been resolved, it remains to be updated https://github.com/kabagouda/multi_select_flutter.git .
If you are in a hurry, you can clone this repository or just use mine : 

```
  multi_select_flutter:
    git:
      url: https://github.com/kabagouda/multi_select_flutter.git
      ref: patch-1 # branch name

```

@CHB61 Please update the package 
Thanks
