### ISSUE TITLE
can't import 'package:multi_select_flutter/multi_select_flutter.dart'

### ISSUE THREAD

**Issue by ronytesler** [CHB61/multi_select_flutter#89]
The import is not working. I get this error:
Target of URI doesn't exist.

yaml file:
```

name: my_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_auth: ^3.3.7
  rxdart: ^0.27.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  multi_select_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

```
